<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RootNamespace>LeakDetectSystem_MVVM</RootNamespace>
    <AssemblyName>LeakDetectSystem_MVVM</AssemblyName>
    <ApplicationIcon />
  </PropertyGroup>
<ItemGroup>
    <!-- .NET Framework 호환성 패키지 추가 -->
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="8.0.0" />    
    <Reference Include="Cognex.VisionPro">
      <HintPath>C:\Program Files\Cognex\VisionPro\ReferencedAssemblies\Cognex.VisionPro.dll</HintPath>
    </Reference>
    <Reference Include="Cognex.VisionPro.Blob">
      <HintPath>C:\Program Files\Cognex\VisionPro\ReferencedAssemblies\Cognex.VisionPro.Blob.dll</HintPath>
    </Reference>
    <Reference Include="Cognex.VisionPro.Caliper">
      <HintPath>C:\Program Files\Cognex\VisionPro\ReferencedAssemblies\Cognex.VisionPro.Caliper.dll</HintPath>
    </Reference>
    <Reference Include="Cognex.VisionPro.Controls">
      <HintPath>C:\Program Files\Cognex\VisionPro\ReferencedAssemblies\Cognex.VisionPro.Controls.dll</HintPath>
    </Reference>
    <Reference Include="Cognex.VisionPro.Dimensioning">
      <HintPath>C:\Program Files\Cognex\VisionPro\ReferencedAssemblies\Cognex.VisionPro.Dimensioning.dll</HintPath>
    </Reference>
    <Reference Include="Cognex.VisionPro.Display.Controls">
      <HintPath>C:\Program Files\Cognex\VisionPro\ReferencedAssemblies\Cognex.VisionPro.Display.Controls.dll</HintPath>
    </Reference>
    <Reference Include="Cognex.VisionPro.ImageFile">
      <HintPath>C:\Program Files\Cognex\VisionPro\ReferencedAssemblies\Cognex.VisionPro.ImageFile.dll</HintPath>
    </Reference>
    <Reference Include="Cognex.VisionPro.ImageProcessing">
      <HintPath>C:\Program Files\Cognex\VisionPro\ReferencedAssemblies\Cognex.VisionPro.ImageProcessing.dll</HintPath>
    </Reference>
    <Reference Include="Cognex.VisionPro.Inspection">
      <HintPath>C:\Program Files\Cognex\VisionPro\ReferencedAssemblies\Cognex.VisionPro.Inspection.dll</HintPath>
    </Reference>
    <Reference Include="Cognex.VisionPro.Interop.Core">
      <HintPath>C:\Program Files\Cognex\VisionPro\ReferencedAssemblies\Cognex.VisionPro.Interop.Core.dll</HintPath>
    </Reference>
    <Reference Include="Cognex.VisionPro.OC">
      <HintPath>C:\Program Files\Cognex\VisionPro\ReferencedAssemblies\Cognex.VisionPro.OC.dll</HintPath>
    </Reference>
    <Reference Include="Cognex.VisionPro.PMAlign">
      <HintPath>C:\Program Files\Cognex\VisionPro\ReferencedAssemblies\Cognex.VisionPro.PMAlign.dll</HintPath>
    </Reference>
    <Reference Include="Cognex.VisionPro.ResultsAnalysis">
      <HintPath>C:\Program Files\Cognex\VisionPro\ReferencedAssemblies\Cognex.VisionPro.ResultsAnalysis.dll</HintPath>
    </Reference>
    <Reference Include="Cognex.VisionPro.ToolGroup">
      <HintPath>C:\Program Files\Cognex\VisionPro\ReferencedAssemblies\Cognex.VisionPro.ToolGroup.dll</HintPath>
    </Reference>
    <Reference Include="Cognex.VisionPro.ToolGroup.Controls">
      <HintPath>C:\Program Files\Cognex\VisionPro\ReferencedAssemblies\Cognex.VisionPro.ToolGroup.Controls.dll</HintPath>
    </Reference>
    <Reference Include="ECS_LightController">
      <HintPath>..\..\..\..\..\..\0.Project\Slurry_VisionSystem_250806\VisionSystem\bin\x64\Debug\ECS_LightController.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
