<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RootNamespace>LeakDetectSystem_MVVM</RootNamespace>
    <AssemblyName>LeakDetectSystem_MVVM</AssemblyName>
    <ApplicationIcon />
  </PropertyGroup>

</Project>
